trigger:
- master

jobs:
- template: .azure/default-build.yml
  parameters:
    agentOs: Windows
    beforeBuild:
    - powershell: "& ./submodules/vcpkg/bootstrap-vcpkg.bat"
      displayName: Bootstrap vcpkg
    - powershell: "& ./submodules/vcpkg/vcpkg.exe install cpprestsdk cpprestsdk:x64-windows"
      displayName: vcpkg install dependencies
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

- template: .azure/default-build.yml
  parameters:
    agentOs: macOs
    beforeBuild:
    - script: brew install gcc boost
    - bash: "./submodules/vcpkg/bootstrap-vcpkg.sh"
      displayName: Bootstrap vcpkg
    - bash: "./submodules/vcpkg/vcpkg install cpprestsdk"
      displayName: vcpkg install dependencies
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

- template: .azure/default-build.yml
  parameters:
    agentOs: Linux
    beforeBuild:
    - script: |
        ./submodules/vcpkg/bootstrap-vcpkg.sh
        sudo ./submodules/vcpkg/vcpkg install cpprestsdk boost-system boost-chrono boost-thread
      displayName: vcpkg install dependencies
    - script: echo Hello, world!
      displayName: 'Run a one-line script'