trigger:
- master

jobs:
- template: .azure/default-build.yml
  parameters:
    agentOs: Windows
    beforeBuild:
    - powershell: "& vcpkg.exe install cpprestsdk cpprestsdk:x64-windows"
      displayName: vcpkg install dependencies

- template: .azure/default-build.yml
  parameters:
    agentOs: macOs
    cmakeRunArgs: -DCMAKE_TOOLCHAIN_FILE=../submodules/vcpkg/scripts/buildsystems/vcpkg.cmake
    beforeBuild:
    - script: brew install gcc boost
    - bash: "./submodules/vcpkg/bootstrap-vcpkg.sh"
      displayName: Bootstrap vcpkg
    - bash: "./submodules/vcpkg/vcpkg install cpprestsdk"
      displayName: vcpkg install dependencies

- template: .azure/default-build.yml
  parameters:
    agentOs: Linux
    beforeBuild:
    - script: sudo vcpkg install cpprestsdk boost-system boost-chrono boost-thread
      displayName: vcpkg install dependencies